### ISSUE TITLE
不是Bug，去除侧边滚动条可能好看点

### ISSUE THREAD

**Issue by DerekSunmo** [Jazee6/cloudflare-ai-web#3]
只是个人感觉好看些和😂
在/page/index.vue文件添加css样式：
```css
::-webkit-scrollbar {
  display: none;
}
```
